alias grf="git reflog"
alias gpsf="git push --force-with-lease"
alias gps="git push"
alias gpl="git pull"
alias gs="git status"
alias ga="git add ."
alias gc="git commit"
alias gca="git commit --amend"
alias gl="git log"
alias glo="git log --oneline"
alias gla="git log --oneline --graph --all"
alias gd="git diff"
alias gb="git branch"
alias grm="git remote"
alias gcm="git checkout master"
alias grb="git rebase"
alias grbi="git rebase -i"
alias gcf="git config"
alias gcfl="git config -l"
alias gcfe="git config --global --edit"
alias grs="git reset"
alias gl1="git log --graph --all --abbrev-commit --date=short --pretty=format:'%C(Yellow)%h %C(Cyan)%cd %C(Green)<%an>%Creset %s %C(Red)%d'"
alias gl2="git log --graph --all --abbrev-commit --date=relative --pretty=format:'%C(Yellow)%h %C(Cyan)%cd %C(Green)<%an>%Creset %s %C(Red)%d'"

export PATH="$PATH:/c/Anaconda3:/c/Anaconda3/Scripts"
alias python="winpty python.exe"